-- ============================================================
-- AI Event Scenario Insight Platform — Supabase 초기 스키마
-- Supabase > SQL Editor 에 전체 붙여넣고 Run 클릭
-- ============================================================

CREATE TABLE IF NOT EXISTS events (
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title         TEXT    NOT NULL,
    url           TEXT    UNIQUE,
    source        TEXT,
    topic         TEXT,
    impact_score  FLOAT   DEFAULT 0,
    trust_score   FLOAT   DEFAULT 0.5,
    tone          FLOAT   DEFAULT 0,
    published_at  TEXT,
    is_active     BOOLEAN DEFAULT TRUE,
    closed_at     TIMESTAMPTZ,
    created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS scenarios (
    id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id       BIGINT  NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    event_summary  TEXT,
    scenario_a     JSONB,
    scenario_b     JSONB,
    scenario_c     JSONB,
    raw_json       JSONB,
    is_published   BOOLEAN     DEFAULT TRUE,
    update_count   INT         DEFAULT 0,
    generated_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_feedback (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    scenario_id BIGINT NOT NULL REFERENCES scenarios(id) ON DELETE CASCADE,
    rating      INT    CHECK (rating BETWEEN 1 AND 5),
    comment     TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 인덱스
CREATE INDEX IF NOT EXISTS idx_events_topic      ON events(topic);
CREATE INDEX IF NOT EXISTS idx_events_active     ON events(is_active);
CREATE INDEX IF NOT EXISTS idx_scenarios_event   ON scenarios(event_id);
CREATE INDEX IF NOT EXISTS idx_scenarios_pub     ON scenarios(is_published);
CREATE INDEX IF NOT EXISTS idx_feedback_scenario ON user_feedback(scenario_id);

-- RLS
ALTER TABLE events        ENABLE ROW LEVEL SECURITY;
ALTER TABLE scenarios     ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_feedback ENABLE ROW LEVEL SECURITY;

CREATE POLICY "events_read"    ON events        FOR SELECT USING (TRUE);
CREATE POLICY "scenarios_read" ON scenarios     FOR SELECT USING (TRUE);
CREATE POLICY "feedback_write" ON user_feedback FOR INSERT WITH CHECK (TRUE);
